blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
            url(r'^$', views.MainPage, name = 'main_page'),
            url(r'^(?P<post_id>[0-9]+)/$', views.PostDetails, name = 'post_details'),
            url(r'^(?P<post_id>[0-9]+)/latestnews/$', views.LatestNews, name = 'latest_news'),

    ]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from polls import urls

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace = 'polls')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^admin/', include(admin.site.urls)),
    
]
#here namespaceing is done sso that after goint to the polls.urls it triggers view.detail
#so to identify which apps detail is being called....also done in html file

polls/urls.py
from django.conf.urls import url
#from django.contrib import admin
from polls import views

urlpatterns = [
               url(r'^$', views.index, name = 'index'),
               url(r'^(?P<question_id>[0-9]+)/$', views.detail, name = 'detail'),
               url(r'^(?P<question_id>[0-9]+)/result/$', views.result, name = 'result'),
               url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote'),
               ]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length = 140)
    body = models.TextField()
    date = models.DateTimeField("Date Published")
def __unicode__(self):
    return self.title

    

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length = 140)
    #body = models.TextField()
    date = models.DateTimeField('date published')
   # def was_published_recently(self):
       # return

    def __unicode__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)
    def __unicode__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template import RequestContext,loader
from blog.models import Post



def MainPage(request):
    Post_list = Post.objects.order_by('date')
    template = loader.get_template('blog/main.html')
    context = RequestContext(request, {
            'Post_list':Post_list}
            )
    return HttpResponse(template.render(context))

def PostDetails(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    return render(request, 'blog/details.html', {'post':post})

def LatestNews(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    return render(request, 'blog/latestnews.html', {'post':post})
              

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from polls.models import Question
from django.template import RequestContext,loader
# in line 1 shortcuts can be written to the long path ie.django.db.models.query.QuerySet.get


def index(request):
    latest_question_list = Question.objects.order_by('date')[:5]
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
           'latest_question_list':latest_question_list})     
    return HttpResponse(template.render(context))

#in latest_question_text we are makin an object with 5 qns
#in output we are setting up the the output of the qns as there will be (,) saperated
#in result, all qns will be in uordered list and a link goes to /polls/qn_id which triggers the detail method defined in url.py


def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id )
    return render(request, 'polls/details.html', {'question': question})

def result(request, question_id):
    return HttpResponse("youre watching the result of question no. %s" % question_id)

def vote(request, question_id):
    return HttpResponse("youre voting the question no. %s" % question_id)

blog/templates/blog/main.html
{% block content %}

{% if Post_list %}
	<h1> Bloggified Blog</h1>
	{% for post in Post_list %}
		<h2><a href = "{% url 'blog:details' Post.id %}"> {% post.title %} </a></h2>
		
		<div class = "post_meta">
		<p>on {% post.date|date: "d/m/y" %} </p>
		</div>
		
		<div class = "post_body">
		
		{% post.body|safe|linebreaks %}
		
		</div>
		
	{% endfor %}
{% endif %}

{% end block content %}

polls/templates/polls/details.html
<h1> {{ question.question_text }} </h1>

{% if error_message %}
	<p><strong> {{error_message}}</strong> </p>
{% endif %}

<form action = "{% url 'polls:vote' question.id%}" method = "post">
	{% csrf_token %}
	{% for choice in question.choice_set.all%}
	<input type = "radio" name = "choice" id = "choice{{forloop.counter}}" value = "choice.id" />
	<label for = "choice{{forloop.counter}}"> {{choice.choice_text}} </label> <br />
	{% endfor %}
	<input type = "submit" value = "vote"/>
	
</form>

polls/templates/polls/index.html
{%if latest_question_list%}
	<ul>
		{%for question in latest_question_list%}
		<li><a href = "{% url 'polls:detail' question.id %}"> {{question.question_text}} </a></li>
		{%endfor%}
	</ul>
	{%else%}
		<p>NO polls questions are there</p>
	{%endif%}